// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package helixWorkerMysql

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.deregisterWorkerStmt, err = db.PrepareContext(ctx, deregisterWorker); err != nil {
		return nil, fmt.Errorf("error preparing query DeregisterWorker: %w", err)
	}
	if q.getAllActiveWorkersByDomainStmt, err = db.PrepareContext(ctx, getAllActiveWorkersByDomain); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllActiveWorkersByDomain: %w", err)
	}
	if q.getWorkerStmt, err = db.PrepareContext(ctx, getWorker); err != nil {
		return nil, fmt.Errorf("error preparing query GetWorker: %w", err)
	}
	if q.getWorkerByWorkerIdAndDomainStmt, err = db.PrepareContext(ctx, getWorkerByWorkerIdAndDomain); err != nil {
		return nil, fmt.Errorf("error preparing query GetWorkerByWorkerIdAndDomain: %w", err)
	}
	if q.getWorkerStatusStmt, err = db.PrepareContext(ctx, getWorkerStatus); err != nil {
		return nil, fmt.Errorf("error preparing query GetWorkerStatus: %w", err)
	}
	if q.markInactiveWorkersStmt, err = db.PrepareContext(ctx, markInactiveWorkers); err != nil {
		return nil, fmt.Errorf("error preparing query MarkInactiveWorkers: %w", err)
	}
	if q.registerWorkerStmt, err = db.PrepareContext(ctx, registerWorker); err != nil {
		return nil, fmt.Errorf("error preparing query RegisterWorker: %w", err)
	}
	if q.sendHeartbeatStmt, err = db.PrepareContext(ctx, sendHeartbeat); err != nil {
		return nil, fmt.Errorf("error preparing query SendHeartbeat: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.deregisterWorkerStmt != nil {
		if cerr := q.deregisterWorkerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deregisterWorkerStmt: %w", cerr)
		}
	}
	if q.getAllActiveWorkersByDomainStmt != nil {
		if cerr := q.getAllActiveWorkersByDomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllActiveWorkersByDomainStmt: %w", cerr)
		}
	}
	if q.getWorkerStmt != nil {
		if cerr := q.getWorkerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWorkerStmt: %w", cerr)
		}
	}
	if q.getWorkerByWorkerIdAndDomainStmt != nil {
		if cerr := q.getWorkerByWorkerIdAndDomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWorkerByWorkerIdAndDomainStmt: %w", cerr)
		}
	}
	if q.getWorkerStatusStmt != nil {
		if cerr := q.getWorkerStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWorkerStatusStmt: %w", cerr)
		}
	}
	if q.markInactiveWorkersStmt != nil {
		if cerr := q.markInactiveWorkersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markInactiveWorkersStmt: %w", cerr)
		}
	}
	if q.registerWorkerStmt != nil {
		if cerr := q.registerWorkerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing registerWorkerStmt: %w", cerr)
		}
	}
	if q.sendHeartbeatStmt != nil {
		if cerr := q.sendHeartbeatStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing sendHeartbeatStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	deregisterWorkerStmt             *sql.Stmt
	getAllActiveWorkersByDomainStmt  *sql.Stmt
	getWorkerStmt                    *sql.Stmt
	getWorkerByWorkerIdAndDomainStmt *sql.Stmt
	getWorkerStatusStmt              *sql.Stmt
	markInactiveWorkersStmt          *sql.Stmt
	registerWorkerStmt               *sql.Stmt
	sendHeartbeatStmt                *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		deregisterWorkerStmt:             q.deregisterWorkerStmt,
		getAllActiveWorkersByDomainStmt:  q.getAllActiveWorkersByDomainStmt,
		getWorkerStmt:                    q.getWorkerStmt,
		getWorkerByWorkerIdAndDomainStmt: q.getWorkerByWorkerIdAndDomainStmt,
		getWorkerStatusStmt:              q.getWorkerStatusStmt,
		markInactiveWorkersStmt:          q.markInactiveWorkersStmt,
		registerWorkerStmt:               q.registerWorkerStmt,
		sendHeartbeatStmt:                q.sendHeartbeatStmt,
	}
}
