// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package helixWorkerMysql

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getWorkerStatusStmt, err = db.PrepareContext(ctx, getWorkerStatus); err != nil {
		return nil, fmt.Errorf("error preparing query GetWorkerStatus: %w", err)
	}
	if q.registerWorkerStmt, err = db.PrepareContext(ctx, registerWorker); err != nil {
		return nil, fmt.Errorf("error preparing query RegisterWorker: %w", err)
	}
	if q.sendHeartbeatStmt, err = db.PrepareContext(ctx, sendHeartbeat); err != nil {
		return nil, fmt.Errorf("error preparing query SendHeartbeat: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getWorkerStatusStmt != nil {
		if cerr := q.getWorkerStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWorkerStatusStmt: %w", cerr)
		}
	}
	if q.registerWorkerStmt != nil {
		if cerr := q.registerWorkerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing registerWorkerStmt: %w", cerr)
		}
	}
	if q.sendHeartbeatStmt != nil {
		if cerr := q.sendHeartbeatStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing sendHeartbeatStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                  DBTX
	tx                  *sql.Tx
	getWorkerStatusStmt *sql.Stmt
	registerWorkerStmt  *sql.Stmt
	sendHeartbeatStmt   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                  tx,
		tx:                  tx,
		getWorkerStatusStmt: q.getWorkerStatusStmt,
		registerWorkerStmt:  q.registerWorkerStmt,
		sendHeartbeatStmt:   q.sendHeartbeatStmt,
	}
}
