// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package helixWorkerMysql

import (
	"database/sql"
	"time"
)

type HelixWorker struct {
	ID              sql.NullInt64 `json:"id"`
	WorkerID        string        `json:"worker_id"`
	Domain          string        `json:"domain"`
	Status          int8          `json:"status"`
	CreatedAt       time.Time     `json:"created_at"`
	LastHeartbeatAt time.Time     `json:"last_heartbeat_at"`
	UpdatedAt       sql.NullTime  `json:"updated_at"`
}
