// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package helixWorkerMysql

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	//DeregisterWorker
	//
	//  UPDATE helix_workers
	//  SET status = 0
	//  WHERE domain = ?
	//    AND worker_id = ?
	DeregisterWorker(ctx context.Context, arg DeregisterWorkerParams) error
	//GetAllActiveWorkersByDomain
	//
	//  SELECT worker_id
	//  FROM helix_workers
	//  WHERE domain = ?
	//    and status = 1
	GetAllActiveWorkersByDomain(ctx context.Context, domain string) ([]string, error)
	//GetWorker
	//
	//  SELECT worker_id, domain, status, created_at, last_heartbeat_at, updated_at
	//  FROM helix_workers
	//  WHERE worker_id = ?
	//    AND domain = ?
	GetWorker(ctx context.Context, arg GetWorkerParams) (*GetWorkerRow, error)
	//GetWorkerByWorkerIdAndDomain
	//
	//  SELECT id, worker_id, domain, status, last_heartbeat_at, created_at, updated_at
	//  FROM helix_workers
	//  WHERE domain = ?
	//    and worker_id = ?
	GetWorkerByWorkerIdAndDomain(ctx context.Context, arg GetWorkerByWorkerIdAndDomainParams) (*HelixWorker, error)
	//GetWorkerStatus
	//
	//  SELECT status
	//  FROM helix_workers
	//  WHERE domain = ?
	//    AND worker_id = ?
	GetWorkerStatus(ctx context.Context, arg GetWorkerStatusParams) (int8, error)
	//MarkInactiveWorkers
	//
	//  UPDATE helix_workers
	//  SET status = 0
	//  WHERE last_heartbeat_at < ?
	//    AND status = 1
	MarkInactiveWorkers(ctx context.Context, lastHeartbeatAt time.Time) error
	//RegisterWorker
	//
	//  INSERT INTO helix_workers (worker_id, domain, status, created_at, last_heartbeat_at)
	//  VALUES (?, ?, 1, ?, ?)
	RegisterWorker(ctx context.Context, arg RegisterWorkerParams) error
	//SendHeartbeat
	//
	//  UPDATE helix_workers
	//  SET last_heartbeat_at = ?
	//  WHERE domain = ?
	//    AND worker_id = ?
	//    AND status = 1
	SendHeartbeat(ctx context.Context, arg SendHeartbeatParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
