// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package helixWorkerMysql

import (
	"context"
	"database/sql"
	"time"
)

const deregisterWorker = `-- name: DeregisterWorker :exec
UPDATE helix_workers
SET status = 0,
    inactive_reason = ?
WHERE domain = ?
  AND worker_id = ?
`

type DeregisterWorkerParams struct {
	InactiveReason sql.NullString `json:"inactive_reason"`
	Domain         string         `json:"domain"`
	WorkerID       string         `json:"worker_id"`
}

// DeregisterWorker
//
//	UPDATE helix_workers
//	SET status = 0,
//	    inactive_reason = ?
//	WHERE domain = ?
//	  AND worker_id = ?
func (q *Queries) DeregisterWorker(ctx context.Context, arg DeregisterWorkerParams) error {
	_, err := q.exec(ctx, q.deregisterWorkerStmt, deregisterWorker, arg.InactiveReason, arg.Domain, arg.WorkerID)
	return err
}

const getAllActiveWorkersByDomain = `-- name: GetAllActiveWorkersByDomain :many
SELECT worker_id
FROM helix_workers
WHERE domain = ?
  and status = 1
`

// GetAllActiveWorkersByDomain
//
//	SELECT worker_id
//	FROM helix_workers
//	WHERE domain = ?
//	  and status = 1
func (q *Queries) GetAllActiveWorkersByDomain(ctx context.Context, domain string) ([]string, error) {
	rows, err := q.query(ctx, q.getAllActiveWorkersByDomainStmt, getAllActiveWorkersByDomain, domain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var worker_id string
		if err := rows.Scan(&worker_id); err != nil {
			return nil, err
		}
		items = append(items, worker_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorker = `-- name: GetWorker :one
SELECT worker_id, domain, status, created_at, last_heartbeat_at, updated_at
FROM helix_workers
WHERE worker_id = ?
  AND domain = ?
`

type GetWorkerParams struct {
	WorkerID string `json:"worker_id"`
	Domain   string `json:"domain"`
}

type GetWorkerRow struct {
	WorkerID        string       `json:"worker_id"`
	Domain          string       `json:"domain"`
	Status          int8         `json:"status"`
	CreatedAt       time.Time    `json:"created_at"`
	LastHeartbeatAt time.Time    `json:"last_heartbeat_at"`
	UpdatedAt       sql.NullTime `json:"updated_at"`
}

// GetWorker
//
//	SELECT worker_id, domain, status, created_at, last_heartbeat_at, updated_at
//	FROM helix_workers
//	WHERE worker_id = ?
//	  AND domain = ?
func (q *Queries) GetWorker(ctx context.Context, arg GetWorkerParams) (*GetWorkerRow, error) {
	row := q.queryRow(ctx, q.getWorkerStmt, getWorker, arg.WorkerID, arg.Domain)
	var i GetWorkerRow
	err := row.Scan(
		&i.WorkerID,
		&i.Domain,
		&i.Status,
		&i.CreatedAt,
		&i.LastHeartbeatAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getWorkerByWorkerIdAndDomain = `-- name: GetWorkerByWorkerIdAndDomain :one
SELECT id, worker_id, domain, status, inactive_reason, last_heartbeat_at, created_at, updated_at
FROM helix_workers
WHERE domain = ?
  and worker_id = ?
`

type GetWorkerByWorkerIdAndDomainParams struct {
	Domain   string `json:"domain"`
	WorkerID string `json:"worker_id"`
}

// GetWorkerByWorkerIdAndDomain
//
//	SELECT id, worker_id, domain, status, inactive_reason, last_heartbeat_at, created_at, updated_at
//	FROM helix_workers
//	WHERE domain = ?
//	  and worker_id = ?
func (q *Queries) GetWorkerByWorkerIdAndDomain(ctx context.Context, arg GetWorkerByWorkerIdAndDomainParams) (*HelixWorker, error) {
	row := q.queryRow(ctx, q.getWorkerByWorkerIdAndDomainStmt, getWorkerByWorkerIdAndDomain, arg.Domain, arg.WorkerID)
	var i HelixWorker
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Domain,
		&i.Status,
		&i.InactiveReason,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getWorkerStatus = `-- name: GetWorkerStatus :one
SELECT status
FROM helix_workers
WHERE domain = ?
  AND worker_id = ?
`

type GetWorkerStatusParams struct {
	Domain   string `json:"domain"`
	WorkerID string `json:"worker_id"`
}

// GetWorkerStatus
//
//	SELECT status
//	FROM helix_workers
//	WHERE domain = ?
//	  AND worker_id = ?
func (q *Queries) GetWorkerStatus(ctx context.Context, arg GetWorkerStatusParams) (int8, error) {
	row := q.queryRow(ctx, q.getWorkerStatusStmt, getWorkerStatus, arg.Domain, arg.WorkerID)
	var status int8
	err := row.Scan(&status)
	return status, err
}

const markInactiveWorkers = `-- name: MarkInactiveWorkers :exec
UPDATE helix_workers
SET status = 0,
    inactive_reason = ?
WHERE last_heartbeat_at < ?
  AND status = 1
`

type MarkInactiveWorkersParams struct {
	InactiveReason  sql.NullString `json:"inactive_reason"`
	LastHeartbeatAt time.Time      `json:"last_heartbeat_at"`
}

// MarkInactiveWorkers
//
//	UPDATE helix_workers
//	SET status = 0,
//	    inactive_reason = ?
//	WHERE last_heartbeat_at < ?
//	  AND status = 1
func (q *Queries) MarkInactiveWorkers(ctx context.Context, arg MarkInactiveWorkersParams) error {
	_, err := q.exec(ctx, q.markInactiveWorkersStmt, markInactiveWorkers, arg.InactiveReason, arg.LastHeartbeatAt)
	return err
}

const registerWorker = `-- name: RegisterWorker :exec
INSERT INTO helix_workers (worker_id, domain, status, created_at, last_heartbeat_at)
VALUES (?, ?, 1, ?, ?)
`

type RegisterWorkerParams struct {
	WorkerID        string    `json:"worker_id"`
	Domain          string    `json:"domain"`
	CreatedAt       time.Time `json:"created_at"`
	LastHeartbeatAt time.Time `json:"last_heartbeat_at"`
}

// RegisterWorker
//
//	INSERT INTO helix_workers (worker_id, domain, status, created_at, last_heartbeat_at)
//	VALUES (?, ?, 1, ?, ?)
func (q *Queries) RegisterWorker(ctx context.Context, arg RegisterWorkerParams) error {
	_, err := q.exec(ctx, q.registerWorkerStmt, registerWorker,
		arg.WorkerID,
		arg.Domain,
		arg.CreatedAt,
		arg.LastHeartbeatAt,
	)
	return err
}

const sendHeartbeat = `-- name: SendHeartbeat :execresult
UPDATE helix_workers
SET last_heartbeat_at = ?
WHERE domain = ?
  AND worker_id = ?
  AND status = 1
`

type SendHeartbeatParams struct {
	LastHeartbeatAt time.Time `json:"last_heartbeat_at"`
	Domain          string    `json:"domain"`
	WorkerID        string    `json:"worker_id"`
}

// SendHeartbeat
//
//	UPDATE helix_workers
//	SET last_heartbeat_at = ?
//	WHERE domain = ?
//	  AND worker_id = ?
//	  AND status = 1
func (q *Queries) SendHeartbeat(ctx context.Context, arg SendHeartbeatParams) (sql.Result, error) {
	return q.exec(ctx, q.sendHeartbeatStmt, sendHeartbeat, arg.LastHeartbeatAt, arg.Domain, arg.WorkerID)
}
