// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package helixWorkerMysql

import (
	"context"
)

type Querier interface {
	//GetWorkerStatus
	//
	//  SELECT status FROM helix_workers
	//  WHERE domain = ? AND worker_id = ?
	GetWorkerStatus(ctx context.Context, arg GetWorkerStatusParams) (string, error)
	//RegisterWorker
	//
	//  INSERT INTO helix_workers (worker_id, domain, status, created_at, last_heartbeat_at)
	//  VALUES (?, ?, 'active', ?, ?)
	RegisterWorker(ctx context.Context, arg RegisterWorkerParams) error
	//SendHeartbeat
	//
	//  UPDATE helix_workers
	//  SET last_heartbeat_at = ?
	//  WHERE domain = ? AND worker_id = ? AND status = 'active'
	SendHeartbeat(ctx context.Context, arg SendHeartbeatParams) error
}

var _ Querier = (*Queries)(nil)
