// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package helixMysql

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.checkLockOwnershipStmt, err = db.PrepareContext(ctx, checkLockOwnership); err != nil {
		return nil, fmt.Errorf("error preparing query CheckLockOwnership: %w", err)
	}
	if q.tryAcquireLockStmt, err = db.PrepareContext(ctx, tryAcquireLock); err != nil {
		return nil, fmt.Errorf("error preparing query TryAcquireLock: %w", err)
	}
	if q.upsertLockStmt, err = db.PrepareContext(ctx, upsertLock); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertLock: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.checkLockOwnershipStmt != nil {
		if cerr := q.checkLockOwnershipStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkLockOwnershipStmt: %w", cerr)
		}
	}
	if q.tryAcquireLockStmt != nil {
		if cerr := q.tryAcquireLockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing tryAcquireLockStmt: %w", cerr)
		}
	}
	if q.upsertLockStmt != nil {
		if cerr := q.upsertLockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertLockStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                     DBTX
	tx                     *sql.Tx
	checkLockOwnershipStmt *sql.Stmt
	tryAcquireLockStmt     *sql.Stmt
	upsertLockStmt         *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                     tx,
		tx:                     tx,
		checkLockOwnershipStmt: q.checkLockOwnershipStmt,
		tryAcquireLockStmt:     q.tryAcquireLockStmt,
		upsertLockStmt:         q.upsertLockStmt,
	}
}
