// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package helixMysql

import (
	"context"
)

type Querier interface {
	//UpsertLock
	//
	//  INSERT INTO helix_locks (lock_key, owner_id, expires_at, status)
	//  VALUES (?, ?, ?, ?)
	//  ON DUPLICATE KEY UPDATE
	//      owner_id = VALUES(owner_id),
	//      expires_at = VALUES(expires_at),
	//      status = VALUES(status),
	//      updated_at = CURRENT_TIMESTAMP
	UpsertLock(ctx context.Context, arg UpsertLockParams) error
}

var _ Querier = (*Queries)(nil)
