// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package helixClusterMysql

import (
	"database/sql"
	"time"
)

type HelixCluster struct {
	ID             uint64         `json:"id"`
	Cluster        string         `json:"cluster"`
	Domain         string         `json:"domain"`
	Tasklist       string         `json:"tasklist"`
	Metadata       sql.NullString `json:"metadata"`
	PartitionCount uint32         `json:"partition_count"`
	Status         int8           `json:"status"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type HelixNode struct {
	ID           uint64         `json:"id"`
	ClusterName  string         `json:"cluster_name"`
	NodeUuid     string         `json:"node_uuid"`
	NodeMetadata sql.NullString `json:"node_metadata"`
	LastHbTime   time.Time      `json:"last_hb_time"`
	Status       int8           `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
