// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"encoding/json"
	"time"
)

type Job struct {
	ID          string
	Domain      string
	Tasklist    string
	PartitionID uint32
	Status      string
	Payload     json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
