// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package database

import (
	"context"
	"encoding/json"
)

const createJob = `-- name: CreateJob :exec
INSERT INTO jobs (id, domain, tasklist, partition_id, status, payload)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateJobParams struct {
	ID          string
	Domain      string
	Tasklist    string
	PartitionID uint32
	Status      string
	Payload     json.RawMessage
}

// Inserts a new job into the jobs table.
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.ExecContext(ctx, createJob,
		arg.ID,
		arg.Domain,
		arg.Tasklist,
		arg.PartitionID,
		arg.Status,
		arg.Payload,
	)
	return err
}

const getNextJob = `-- name: GetNextJob :one
SELECT id
FROM jobs
WHERE domain = ?
  AND tasklist = ?
  AND partition_id = ?
  AND status = 'created'
ORDER BY domain, tasklist, partition_id, status, id ASC
LIMIT 1
`

type GetNextJobParams struct {
	Domain      string
	Tasklist    string
	PartitionID uint32
}

// Retrieves the next pending job for a specific partition, ordered by ID.
// This is the core query for our consumer.
func (q *Queries) GetNextJob(ctx context.Context, arg GetNextJobParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getNextJob, arg.Domain, arg.Tasklist, arg.PartitionID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getNextJobForUpdate = `-- name: GetNextJobForUpdate :one
SELECT id
FROM jobs
WHERE domain = ?
  AND tasklist = ?
  AND partition_id = ?
  AND status = 'created'
ORDER BY domain, tasklist, partition_id, status, id ASC
LIMIT 1 for update skip locked
`

type GetNextJobForUpdateParams struct {
	Domain      string
	Tasklist    string
	PartitionID uint32
}

// Retrieves the next pending job for a specific partition using a pessimistic lock.
func (q *Queries) GetNextJobForUpdate(ctx context.Context, arg GetNextJobForUpdateParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getNextJobForUpdate, arg.Domain, arg.Tasklist, arg.PartitionID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getNextJobMin = `-- name: GetNextJobMin :one
SELECT MIN(id)
FROM jobs
WHERE domain = ?
  AND tasklist = ?
  AND partition_id = ?
  AND status = 'created'
`

type GetNextJobMinParams struct {
	Domain      string
	Tasklist    string
	PartitionID uint32
}

// Retrieves the next pending job for a specific partition using a MIN(id) subquery.
func (q *Queries) GetNextJobMin(ctx context.Context, arg GetNextJobMinParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getNextJobMin, arg.Domain, arg.Tasklist, arg.PartitionID)
	var min interface{}
	err := row.Scan(&min)
	return min, err
}

const getNextJobMinForUpdate = `-- name: GetNextJobMinForUpdate :one
SELECT MIN(id)
FROM jobs
WHERE domain = ?
  AND tasklist = ?
  AND partition_id = ?
  AND status = 'created' for update skip locked
`

type GetNextJobMinForUpdateParams struct {
	Domain      string
	Tasklist    string
	PartitionID uint32
}

// Retrieves the next pending job for a specific partition using a MIN(id) subquery and a pessimistic lock.
func (q *Queries) GetNextJobMinForUpdate(ctx context.Context, arg GetNextJobMinForUpdateParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getNextJobMinForUpdate, arg.Domain, arg.Tasklist, arg.PartitionID)
	var min interface{}
	err := row.Scan(&min)
	return min, err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs
SET status = ?
WHERE id = ?
`

type UpdateJobStatusParams struct {
	Status string
	ID     string
}

// Updates the status of a specific job.
func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJobStatus, arg.Status, arg.ID)
	return err
}
