// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"
)

type HelixWorker struct {
	ID              sql.NullInt64
	WorkerID        string
	Domain          string
	Status          string
	CreatedAt       time.Time
	LastHeartbeatAt time.Time
}
