// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package database

import (
	"context"
	"time"
)

const getWorkerStatus = `-- name: GetWorkerStatus :one
SELECT status FROM helix_workers
WHERE domain = ? AND worker_id = ?
`

type GetWorkerStatusParams struct {
	Domain   string
	WorkerID string
}

func (q *Queries) GetWorkerStatus(ctx context.Context, arg GetWorkerStatusParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getWorkerStatus, arg.Domain, arg.WorkerID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const registerWorker = `-- name: RegisterWorker :exec
INSERT INTO helix_workers (worker_id, domain, status, created_at, last_heartbeat_at)
VALUES (?, ?, 'active', ?, ?)
`

type RegisterWorkerParams struct {
	WorkerID        string
	Domain          string
	CreatedAt       time.Time
	LastHeartbeatAt time.Time
}

func (q *Queries) RegisterWorker(ctx context.Context, arg RegisterWorkerParams) error {
	_, err := q.db.ExecContext(ctx, registerWorker,
		arg.WorkerID,
		arg.Domain,
		arg.CreatedAt,
		arg.LastHeartbeatAt,
	)
	return err
}

const sendHeartbeat = `-- name: SendHeartbeat :exec
UPDATE helix_workers
SET last_heartbeat_at = ?
WHERE domain = ? AND worker_id = ? AND status = 'active'
`

type SendHeartbeatParams struct {
	LastHeartbeatAt time.Time
	Domain          string
	WorkerID        string
}

func (q *Queries) SendHeartbeat(ctx context.Context, arg SendHeartbeatParams) error {
	_, err := q.db.ExecContext(ctx, sendHeartbeat, arg.LastHeartbeatAt, arg.Domain, arg.WorkerID)
	return err
}
