// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Domain struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Partition struct {
	ID        int64
	QueueID   int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Queue struct {
	ID        int64
	DomainID  int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
