// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package helixDomainMysql

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.acquireLockStmt, err = db.PrepareContext(ctx, acquireLock); err != nil {
		return nil, fmt.Errorf("error preparing query AcquireLock: %w", err)
	}
	if q.getDomainByDomainAndTasklistStmt, err = db.PrepareContext(ctx, getDomainByDomainAndTasklist); err != nil {
		return nil, fmt.Errorf("error preparing query GetDomainByDomainAndTasklist: %w", err)
	}
	if q.getDomainsByDomainStmt, err = db.PrepareContext(ctx, getDomainsByDomain); err != nil {
		return nil, fmt.Errorf("error preparing query GetDomainsByDomain: %w", err)
	}
	if q.insertDomainWorkerStmt, err = db.PrepareContext(ctx, insertDomainWorker); err != nil {
		return nil, fmt.Errorf("error preparing query InsertDomainWorker: %w", err)
	}
	if q.upsertTasklistStmt, err = db.PrepareContext(ctx, upsertTasklist); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertTasklist: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.acquireLockStmt != nil {
		if cerr := q.acquireLockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing acquireLockStmt: %w", cerr)
		}
	}
	if q.getDomainByDomainAndTasklistStmt != nil {
		if cerr := q.getDomainByDomainAndTasklistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDomainByDomainAndTasklistStmt: %w", cerr)
		}
	}
	if q.getDomainsByDomainStmt != nil {
		if cerr := q.getDomainsByDomainStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDomainsByDomainStmt: %w", cerr)
		}
	}
	if q.insertDomainWorkerStmt != nil {
		if cerr := q.insertDomainWorkerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertDomainWorkerStmt: %w", cerr)
		}
	}
	if q.upsertTasklistStmt != nil {
		if cerr := q.upsertTasklistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertTasklistStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	acquireLockStmt                  *sql.Stmt
	getDomainByDomainAndTasklistStmt *sql.Stmt
	getDomainsByDomainStmt           *sql.Stmt
	insertDomainWorkerStmt           *sql.Stmt
	upsertTasklistStmt               *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		acquireLockStmt:                  q.acquireLockStmt,
		getDomainByDomainAndTasklistStmt: q.getDomainByDomainAndTasklistStmt,
		getDomainsByDomainStmt:           q.getDomainsByDomainStmt,
		insertDomainWorkerStmt:           q.insertDomainWorkerStmt,
		upsertTasklistStmt:               q.upsertTasklistStmt,
	}
}
