// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package helixDomainMysql

import (
	"database/sql"
	"time"
)

type HelixDomain struct {
	ID             uint64         `json:"id"`
	Domain         string         `json:"domain"`
	Tasklist       string         `json:"tasklist"`
	Metadata       sql.NullString `json:"metadata"`
	PartitionCount uint32         `json:"partition_count"`
	Status         int8           `json:"status"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}
