// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package helixDomainMysql

import (
	"context"
	"database/sql"
)

const getDomainByDomainAndTasklist = `-- name: GetDomainByDomainAndTasklist :one
SELECT /*+ MAX_EXECUTION_TIME(1000) */
    id,
    domain,
    tasklist,
    metadata,
    partition_count,
    status,
    created_at,
    updated_at
FROM helix_domain
WHERE domain = ?
  AND tasklist = ?
  AND status = 1
`

type GetDomainByDomainAndTasklistParams struct {
	Domain   string `json:"domain"`
	Tasklist string `json:"tasklist"`
}

// GetDomainByDomainAndTasklist
//
//	SELECT /*+ MAX_EXECUTION_TIME(1000) */
//	    id,
//	    domain,
//	    tasklist,
//	    metadata,
//	    partition_count,
//	    status,
//	    created_at,
//	    updated_at
//	FROM helix_domain
//	WHERE domain = ?
//	  AND tasklist = ?
//	  AND status = 1
func (q *Queries) GetDomainByDomainAndTasklist(ctx context.Context, arg GetDomainByDomainAndTasklistParams) (*HelixDomain, error) {
	row := q.queryRow(ctx, q.getDomainByDomainAndTasklistStmt, getDomainByDomainAndTasklist, arg.Domain, arg.Tasklist)
	var i HelixDomain
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Tasklist,
		&i.Metadata,
		&i.PartitionCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getDomainsByDomain = `-- name: GetDomainsByDomain :many
SELECT /*+ MAX_EXECUTION_TIME(1000) */
    id,
    domain,
    tasklist,
    metadata,
    partition_count,
    status,
    created_at,
    updated_at
FROM helix_domain
WHERE domain = ?
  AND status = 1
`

// GetDomainsByDomain
//
//	SELECT /*+ MAX_EXECUTION_TIME(1000) */
//	    id,
//	    domain,
//	    tasklist,
//	    metadata,
//	    partition_count,
//	    status,
//	    created_at,
//	    updated_at
//	FROM helix_domain
//	WHERE domain = ?
//	  AND status = 1
func (q *Queries) GetDomainsByDomain(ctx context.Context, domain string) ([]*HelixDomain, error) {
	rows, err := q.query(ctx, q.getDomainsByDomainStmt, getDomainsByDomain, domain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*HelixDomain{}
	for rows.Next() {
		var i HelixDomain
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Tasklist,
			&i.Metadata,
			&i.PartitionCount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTasklist = `-- name: UpsertTasklist :exec
INSERT /*+ MAX_EXECUTION_TIME(1000) */
INTO helix_domain (domain, tasklist, metadata, partition_count, status)
VALUES (?, ?, ?, ?, 1)
ON DUPLICATE KEY UPDATE metadata        = VALUES(metadata),
                        partition_count = VALUES(partition_count),
                        status          = 1
`

type UpsertTasklistParams struct {
	Domain         string         `json:"domain"`
	Tasklist       string         `json:"tasklist"`
	Metadata       sql.NullString `json:"metadata"`
	PartitionCount uint32         `json:"partition_count"`
}

// UpsertTasklist
//
//	INSERT /*+ MAX_EXECUTION_TIME(1000) */
//	INTO helix_domain (domain, tasklist, metadata, partition_count, status)
//	VALUES (?, ?, ?, ?, 1)
//	ON DUPLICATE KEY UPDATE metadata        = VALUES(metadata),
//	                        partition_count = VALUES(partition_count),
//	                        status          = 1
func (q *Queries) UpsertTasklist(ctx context.Context, arg UpsertTasklistParams) error {
	_, err := q.exec(ctx, q.upsertTasklistStmt, upsertTasklist,
		arg.Domain,
		arg.Tasklist,
		arg.Metadata,
		arg.PartitionCount,
	)
	return err
}
