// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package helixDomainMysql

import (
	"context"
)

type Querier interface {
	//GetDomainByDomainAndTasklist
	//
	//  SELECT /*+ MAX_EXECUTION_TIME(1000) */
	//      id,
	//      domain,
	//      tasklist,
	//      metadata,
	//      partition_count,
	//      status,
	//      created_at,
	//      updated_at
	//  FROM helix_domain
	//  WHERE domain = ?
	//    AND tasklist = ?
	//    AND status = 1
	GetDomainByDomainAndTasklist(ctx context.Context, arg GetDomainByDomainAndTasklistParams) (*HelixDomain, error)
	//GetDomainsByDomain
	//
	//  SELECT /*+ MAX_EXECUTION_TIME(1000) */
	//      id,
	//      domain,
	//      tasklist,
	//      metadata,
	//      partition_count,
	//      status,
	//      created_at,
	//      updated_at
	//  FROM helix_domain
	//  WHERE domain = ?
	//    AND status = 1
	GetDomainsByDomain(ctx context.Context, domain string) ([]*HelixDomain, error)
	//UpsertTasklist
	//
	//  INSERT /*+ MAX_EXECUTION_TIME(1000) */
	//  INTO helix_domain (domain, tasklist, metadata, partition_count, status)
	//  VALUES (?, ?, ?, ?, 1)
	//  ON DUPLICATE KEY UPDATE metadata        = VALUES(metadata),
	//                          partition_count = VALUES(partition_count),
	//                          status          = 1
	UpsertTasklist(ctx context.Context, arg UpsertTasklistParams) error
}

var _ Querier = (*Queries)(nil)
