// Code generated by MockGen. DO NOT EDIT.
// Source: api.go
//
// Generated by this command:
//
//	mockgen -source=api.go -destination=mocks.go -package=processor
//

// Package processor is a generated GoMock package.
package processor

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDomainTasklistProcessor is a mock of DomainTasklistProcessor interface.
type MockDomainTasklistProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockDomainTasklistProcessorMockRecorder
	isgomock struct{}
}

// MockDomainTasklistProcessorMockRecorder is the mock recorder for MockDomainTasklistProcessor.
type MockDomainTasklistProcessorMockRecorder struct {
	mock *MockDomainTasklistProcessor
}

// NewMockDomainTasklistProcessor creates a new mock instance.
func NewMockDomainTasklistProcessor(ctrl *gomock.Controller) *MockDomainTasklistProcessor {
	mock := &MockDomainTasklistProcessor{ctrl: ctrl}
	mock.recorder = &MockDomainTasklistProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainTasklistProcessor) EXPECT() *MockDomainTasklistProcessorMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockDomainTasklistProcessor) Process(ctx context.Context, request DomainTasklistProcessRequest) (*DomainTasklistProcessResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, request)
	ret0, _ := ret[0].(*DomainTasklistProcessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockDomainTasklistProcessorMockRecorder) Process(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockDomainTasklistProcessor)(nil).Process), ctx, request)
}

// Stop mocks base method.
func (m *MockDomainTasklistProcessor) Stop(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockDomainTasklistProcessorMockRecorder) Stop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockDomainTasklistProcessor)(nil).Stop), arg0)
}

// MockTasklistProcessor is a mock of TasklistProcessor interface.
type MockTasklistProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockTasklistProcessorMockRecorder
	isgomock struct{}
}

// MockTasklistProcessorMockRecorder is the mock recorder for MockTasklistProcessor.
type MockTasklistProcessorMockRecorder struct {
	mock *MockTasklistProcessor
}

// NewMockTasklistProcessor creates a new mock instance.
func NewMockTasklistProcessor(ctrl *gomock.Controller) *MockTasklistProcessor {
	mock := &MockTasklistProcessor{ctrl: ctrl}
	mock.recorder = &MockTasklistProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTasklistProcessor) EXPECT() *MockTasklistProcessorMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockTasklistProcessor) Start(ctx context.Context) (*TasklistProcessResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(*TasklistProcessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockTasklistProcessorMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockTasklistProcessor)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockTasklistProcessor) Stop(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockTasklistProcessorMockRecorder) Stop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockTasklistProcessor)(nil).Stop), arg0)
}
