// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package helixCoordinatorMysql

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getAllPartitionForDomainAndTaskListStmt, err = db.PrepareContext(ctx, getAllPartitionForDomainAndTaskList); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllPartitionForDomainAndTaskList: %w", err)
	}
	if q.getAllValidPartitionForDomainAndTaskListStmt, err = db.PrepareContext(ctx, getAllValidPartitionForDomainAndTaskList); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllValidPartitionForDomainAndTaskList: %w", err)
	}
	if q.getPartitionByOwnerIdStmt, err = db.PrepareContext(ctx, getPartitionByOwnerId); err != nil {
		return nil, fmt.Errorf("error preparing query GetPartitionByOwnerId: %w", err)
	}
	if q.getValidPartitionByOwnerIdStmt, err = db.PrepareContext(ctx, getValidPartitionByOwnerId); err != nil {
		return nil, fmt.Errorf("error preparing query GetValidPartitionByOwnerId: %w", err)
	}
	if q.markPartitionAssignedStmt, err = db.PrepareContext(ctx, markPartitionAssigned); err != nil {
		return nil, fmt.Errorf("error preparing query MarkPartitionAssigned: %w", err)
	}
	if q.markPartitionInactiveStmt, err = db.PrepareContext(ctx, markPartitionInactive); err != nil {
		return nil, fmt.Errorf("error preparing query MarkPartitionInactive: %w", err)
	}
	if q.markPartitionUnassignedStmt, err = db.PrepareContext(ctx, markPartitionUnassigned); err != nil {
		return nil, fmt.Errorf("error preparing query MarkPartitionUnassigned: %w", err)
	}
	if q.upsertPartitionStmt, err = db.PrepareContext(ctx, upsertPartition); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertPartition: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getAllPartitionForDomainAndTaskListStmt != nil {
		if cerr := q.getAllPartitionForDomainAndTaskListStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllPartitionForDomainAndTaskListStmt: %w", cerr)
		}
	}
	if q.getAllValidPartitionForDomainAndTaskListStmt != nil {
		if cerr := q.getAllValidPartitionForDomainAndTaskListStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllValidPartitionForDomainAndTaskListStmt: %w", cerr)
		}
	}
	if q.getPartitionByOwnerIdStmt != nil {
		if cerr := q.getPartitionByOwnerIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPartitionByOwnerIdStmt: %w", cerr)
		}
	}
	if q.getValidPartitionByOwnerIdStmt != nil {
		if cerr := q.getValidPartitionByOwnerIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getValidPartitionByOwnerIdStmt: %w", cerr)
		}
	}
	if q.markPartitionAssignedStmt != nil {
		if cerr := q.markPartitionAssignedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markPartitionAssignedStmt: %w", cerr)
		}
	}
	if q.markPartitionInactiveStmt != nil {
		if cerr := q.markPartitionInactiveStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markPartitionInactiveStmt: %w", cerr)
		}
	}
	if q.markPartitionUnassignedStmt != nil {
		if cerr := q.markPartitionUnassignedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markPartitionUnassignedStmt: %w", cerr)
		}
	}
	if q.upsertPartitionStmt != nil {
		if cerr := q.upsertPartitionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertPartitionStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                           DBTX
	tx                                           *sql.Tx
	getAllPartitionForDomainAndTaskListStmt      *sql.Stmt
	getAllValidPartitionForDomainAndTaskListStmt *sql.Stmt
	getPartitionByOwnerIdStmt                    *sql.Stmt
	getValidPartitionByOwnerIdStmt               *sql.Stmt
	markPartitionAssignedStmt                    *sql.Stmt
	markPartitionInactiveStmt                    *sql.Stmt
	markPartitionUnassignedStmt                  *sql.Stmt
	upsertPartitionStmt                          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                      tx,
		tx:                                      tx,
		getAllPartitionForDomainAndTaskListStmt: q.getAllPartitionForDomainAndTaskListStmt,
		getAllValidPartitionForDomainAndTaskListStmt: q.getAllValidPartitionForDomainAndTaskListStmt,
		getPartitionByOwnerIdStmt:                    q.getPartitionByOwnerIdStmt,
		getValidPartitionByOwnerIdStmt:               q.getValidPartitionByOwnerIdStmt,
		markPartitionAssignedStmt:                    q.markPartitionAssignedStmt,
		markPartitionInactiveStmt:                    q.markPartitionInactiveStmt,
		markPartitionUnassignedStmt:                  q.markPartitionUnassignedStmt,
		upsertPartitionStmt:                          q.upsertPartitionStmt,
	}
}
