// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package helixCoordinatorMysql

import (
	"database/sql"
	"time"
)

type HelixWorkerPartitionMapping struct {
	ID        uint64         `json:"id"`
	Domain    string         `json:"domain"`
	Tasklist  string         `json:"tasklist"`
	OwnerID   string         `json:"owner_id"`
	Status    string         `json:"status"`
	Metadata  sql.NullString `json:"metadata"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
