// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package helixCoordinatorMysql

import (
	"context"
)

type Querier interface {
	//GetAllPartitionForDomainAndTaskList
	//
	//  SELECT /*+ MAX_EXECUTION_TIME(1000) */
	//      id, domain, tasklist, owner_id, status, metadata, created_at, updated_at
	//  FROM helix_worker_partition_mapping
	//  WHERE domain = ?
	//    AND tasklist = ?
	GetAllPartitionForDomainAndTaskList(ctx context.Context, arg GetAllPartitionForDomainAndTaskListParams) ([]*HelixWorkerPartitionMapping, error)
	//GetAllValidPartitionForDomainAndTaskList
	//
	//  SELECT /*+ MAX_EXECUTION_TIME(1000) */
	//      id, domain, tasklist, owner_id, status, metadata, created_at, updated_at
	//  FROM helix_worker_partition_mapping
	//  WHERE domain = ?
	//    AND tasklist = ?
	//    AND status in (1, 2)
	GetAllValidPartitionForDomainAndTaskList(ctx context.Context, arg GetAllValidPartitionForDomainAndTaskListParams) ([]*HelixWorkerPartitionMapping, error)
	//GetPartitionByOwnerId
	//
	//  SELECT /*+ MAX_EXECUTION_TIME(1000) */
	//      id, domain, tasklist, owner_id, status, metadata, created_at, updated_at
	//  FROM helix_worker_partition_mapping
	//  WHERE domain = ?
	//    AND tasklist = ?
	GetPartitionByOwnerId(ctx context.Context, arg GetPartitionByOwnerIdParams) (*HelixWorkerPartitionMapping, error)
	//GetValidPartitionByOwnerId
	//
	//  SELECT /*+ MAX_EXECUTION_TIME(1000) */
	//      id, domain, tasklist, owner_id, status, metadata, created_at, updated_at
	//  FROM helix_worker_partition_mapping
	//  WHERE domain = ?
	//    AND tasklist = ?
	//    AND status in (1, 2)
	GetValidPartitionByOwnerId(ctx context.Context, arg GetValidPartitionByOwnerIdParams) (*HelixWorkerPartitionMapping, error)
	//MarkPartitionAssigned
	//
	//  UPDATE helix_worker_partition_mapping
	//  SET status=1
	//  WHERE domain = ?
	//    and tasklist = ?
	MarkPartitionAssigned(ctx context.Context, arg MarkPartitionAssignedParams) error
	//MarkPartitionInactive
	//
	//  UPDATE helix_worker_partition_mapping
	//  SET status=0
	//  WHERE domain = ?
	//    and tasklist = ?
	MarkPartitionInactive(ctx context.Context, arg MarkPartitionInactiveParams) error
	//MarkPartitionUnassigned
	//
	//  UPDATE helix_worker_partition_mapping
	//  SET status=2
	//  WHERE domain = ?
	//    and tasklist = ?
	MarkPartitionUnassigned(ctx context.Context, arg MarkPartitionUnassignedParams) error
	//UpsertPartition
	//
	//  INSERT /*+ MAX_EXECUTION_TIME(1000) */
	//  INTO helix_worker_partition_mapping(domain, tasklist, owner_id, metadata, status)
	//  VALUES (?, ?, ?, ?, ?)
	//  ON DUPLICATE KEY UPDATE metadata=VALUES(metadata),
	//                          status=VALUES(status),
	//                          owner_id=VALUES(owner_id)
	UpsertPartition(ctx context.Context, arg UpsertPartitionParams) error
}

var _ Querier = (*Queries)(nil)
