// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package helixCoordinatorMysql

import (
	"context"
	"database/sql"
)

const getAllPartitionForDomainAndTaskList = `-- name: GetAllPartitionForDomainAndTaskList :many
SELECT /*+ MAX_EXECUTION_TIME(1000) */
    id, domain, tasklist, owner_id, status, metadata, created_at, updated_at
FROM helix_worker_partition_mapping
WHERE domain = ?
  AND tasklist = ?
`

type GetAllPartitionForDomainAndTaskListParams struct {
	Domain   string `json:"domain"`
	Tasklist string `json:"tasklist"`
}

// GetAllPartitionForDomainAndTaskList
//
//	SELECT /*+ MAX_EXECUTION_TIME(1000) */
//	    id, domain, tasklist, owner_id, status, metadata, created_at, updated_at
//	FROM helix_worker_partition_mapping
//	WHERE domain = ?
//	  AND tasklist = ?
func (q *Queries) GetAllPartitionForDomainAndTaskList(ctx context.Context, arg GetAllPartitionForDomainAndTaskListParams) ([]*HelixWorkerPartitionMapping, error) {
	rows, err := q.query(ctx, q.getAllPartitionForDomainAndTaskListStmt, getAllPartitionForDomainAndTaskList, arg.Domain, arg.Tasklist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*HelixWorkerPartitionMapping{}
	for rows.Next() {
		var i HelixWorkerPartitionMapping
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Tasklist,
			&i.OwnerID,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllValidPartitionForDomainAndTaskList = `-- name: GetAllValidPartitionForDomainAndTaskList :many
SELECT /*+ MAX_EXECUTION_TIME(1000) */
    id, domain, tasklist, owner_id, status, metadata, created_at, updated_at
FROM helix_worker_partition_mapping
WHERE domain = ?
  AND tasklist = ?
  AND status in (1, 2)
`

type GetAllValidPartitionForDomainAndTaskListParams struct {
	Domain   string `json:"domain"`
	Tasklist string `json:"tasklist"`
}

// GetAllValidPartitionForDomainAndTaskList
//
//	SELECT /*+ MAX_EXECUTION_TIME(1000) */
//	    id, domain, tasklist, owner_id, status, metadata, created_at, updated_at
//	FROM helix_worker_partition_mapping
//	WHERE domain = ?
//	  AND tasklist = ?
//	  AND status in (1, 2)
func (q *Queries) GetAllValidPartitionForDomainAndTaskList(ctx context.Context, arg GetAllValidPartitionForDomainAndTaskListParams) ([]*HelixWorkerPartitionMapping, error) {
	rows, err := q.query(ctx, q.getAllValidPartitionForDomainAndTaskListStmt, getAllValidPartitionForDomainAndTaskList, arg.Domain, arg.Tasklist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*HelixWorkerPartitionMapping{}
	for rows.Next() {
		var i HelixWorkerPartitionMapping
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Tasklist,
			&i.OwnerID,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartitionByOwnerId = `-- name: GetPartitionByOwnerId :one
SELECT /*+ MAX_EXECUTION_TIME(1000) */
    id, domain, tasklist, owner_id, status, metadata, created_at, updated_at
FROM helix_worker_partition_mapping
WHERE domain = ?
  AND tasklist = ?
`

type GetPartitionByOwnerIdParams struct {
	Domain   string `json:"domain"`
	Tasklist string `json:"tasklist"`
}

// GetPartitionByOwnerId
//
//	SELECT /*+ MAX_EXECUTION_TIME(1000) */
//	    id, domain, tasklist, owner_id, status, metadata, created_at, updated_at
//	FROM helix_worker_partition_mapping
//	WHERE domain = ?
//	  AND tasklist = ?
func (q *Queries) GetPartitionByOwnerId(ctx context.Context, arg GetPartitionByOwnerIdParams) (*HelixWorkerPartitionMapping, error) {
	row := q.queryRow(ctx, q.getPartitionByOwnerIdStmt, getPartitionByOwnerId, arg.Domain, arg.Tasklist)
	var i HelixWorkerPartitionMapping
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Tasklist,
		&i.OwnerID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getValidPartitionByOwnerId = `-- name: GetValidPartitionByOwnerId :one
SELECT /*+ MAX_EXECUTION_TIME(1000) */
    id, domain, tasklist, owner_id, status, metadata, created_at, updated_at
FROM helix_worker_partition_mapping
WHERE domain = ?
  AND tasklist = ?
  AND status in (1, 2)
`

type GetValidPartitionByOwnerIdParams struct {
	Domain   string `json:"domain"`
	Tasklist string `json:"tasklist"`
}

// GetValidPartitionByOwnerId
//
//	SELECT /*+ MAX_EXECUTION_TIME(1000) */
//	    id, domain, tasklist, owner_id, status, metadata, created_at, updated_at
//	FROM helix_worker_partition_mapping
//	WHERE domain = ?
//	  AND tasklist = ?
//	  AND status in (1, 2)
func (q *Queries) GetValidPartitionByOwnerId(ctx context.Context, arg GetValidPartitionByOwnerIdParams) (*HelixWorkerPartitionMapping, error) {
	row := q.queryRow(ctx, q.getValidPartitionByOwnerIdStmt, getValidPartitionByOwnerId, arg.Domain, arg.Tasklist)
	var i HelixWorkerPartitionMapping
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Tasklist,
		&i.OwnerID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const markPartitionAssigned = `-- name: MarkPartitionAssigned :exec
UPDATE helix_worker_partition_mapping
SET status=1
WHERE domain = ?
  and tasklist = ?
`

type MarkPartitionAssignedParams struct {
	Domain   string `json:"domain"`
	Tasklist string `json:"tasklist"`
}

// MarkPartitionAssigned
//
//	UPDATE helix_worker_partition_mapping
//	SET status=1
//	WHERE domain = ?
//	  and tasklist = ?
func (q *Queries) MarkPartitionAssigned(ctx context.Context, arg MarkPartitionAssignedParams) error {
	_, err := q.exec(ctx, q.markPartitionAssignedStmt, markPartitionAssigned, arg.Domain, arg.Tasklist)
	return err
}

const markPartitionInactive = `-- name: MarkPartitionInactive :exec
UPDATE helix_worker_partition_mapping
SET status=0
WHERE domain = ?
  and tasklist = ?
  and status = 1
`

type MarkPartitionInactiveParams struct {
	Domain   string `json:"domain"`
	Tasklist string `json:"tasklist"`
}

// MarkPartitionInactive
//
//	UPDATE helix_worker_partition_mapping
//	SET status=0
//	WHERE domain = ?
//	  and tasklist = ?
//	  and status = 1
func (q *Queries) MarkPartitionInactive(ctx context.Context, arg MarkPartitionInactiveParams) error {
	_, err := q.exec(ctx, q.markPartitionInactiveStmt, markPartitionInactive, arg.Domain, arg.Tasklist)
	return err
}

const markPartitionUnassigned = `-- name: MarkPartitionUnassigned :exec
UPDATE helix_worker_partition_mapping
SET status=2
WHERE domain = ?
  and tasklist = ?
`

type MarkPartitionUnassignedParams struct {
	Domain   string `json:"domain"`
	Tasklist string `json:"tasklist"`
}

// MarkPartitionUnassigned
//
//	UPDATE helix_worker_partition_mapping
//	SET status=2
//	WHERE domain = ?
//	  and tasklist = ?
func (q *Queries) MarkPartitionUnassigned(ctx context.Context, arg MarkPartitionUnassignedParams) error {
	_, err := q.exec(ctx, q.markPartitionUnassignedStmt, markPartitionUnassigned, arg.Domain, arg.Tasklist)
	return err
}

const upsertPartition = `-- name: UpsertPartition :exec
INSERT /*+ MAX_EXECUTION_TIME(1000) */
INTO helix_worker_partition_mapping(domain, tasklist, owner_id, metadata, status)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE metadata=VALUES(metadata),
                        status=VALUES(status),
                        owner_id=VALUES(owner_id)
`

type UpsertPartitionParams struct {
	Domain   string         `json:"domain"`
	Tasklist string         `json:"tasklist"`
	OwnerID  string         `json:"owner_id"`
	Metadata sql.NullString `json:"metadata"`
	Status   int8           `json:"status"`
}

// UpsertPartition
//
//	INSERT /*+ MAX_EXECUTION_TIME(1000) */
//	INTO helix_worker_partition_mapping(domain, tasklist, owner_id, metadata, status)
//	VALUES (?, ?, ?, ?, ?)
//	ON DUPLICATE KEY UPDATE metadata=VALUES(metadata),
//	                        status=VALUES(status),
//	                        owner_id=VALUES(owner_id)
func (q *Queries) UpsertPartition(ctx context.Context, arg UpsertPartitionParams) error {
	_, err := q.exec(ctx, q.upsertPartitionStmt, upsertPartition,
		arg.Domain,
		arg.Tasklist,
		arg.OwnerID,
		arg.Metadata,
		arg.Status,
	)
	return err
}
