// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package helixClusterMysql

import (
	"context"
	"database/sql"
	"time"
)

const acquireLock = `-- name: AcquireLock :execresult
INSERT /*+ MAX_EXECUTION_TIME(1000) */ INTO helix_locks
    (domain, lock_key, owner_id, expires_at, epoch, status)
VALUES (?, ?, ?, ?, 1, 1)
ON DUPLICATE KEY UPDATE
    status = IF((@original_owner_id := owner_id) IS NOT NULL AND (@original_expires_at := expires_at) IS NOT NULL, 1, 1),
    owner_id = IF(
        @original_owner_id = VALUES(owner_id) OR @original_expires_at < ?,
        VALUES(owner_id),
        owner_id
    ),
    expires_at = IF(
        @original_owner_id = VALUES(owner_id) OR @original_expires_at < ?,
        VALUES(expires_at),
        expires_at
    ),
    epoch = IF(
        @original_owner_id != VALUES(owner_id) AND @original_expires_at < ?,
        epoch + 1,
        epoch
    )
`

type AcquireLockParams struct {
	Domain    string      `json:"domain"`
	LockKey   string      `json:"lock_key"`
	OwnerID   string      `json:"owner_id"`
	ExpiresAt time.Time   `json:"expires_at"`
	Column5   interface{} `json:"column_5"`
	Column6   interface{} `json:"column_6"`
	Column7   interface{} `json:"column_7"`
}

// AcquireLock
//
//	INSERT /*+ MAX_EXECUTION_TIME(1000) */ INTO helix_locks
//	    (domain, lock_key, owner_id, expires_at, epoch, status)
//	VALUES (?, ?, ?, ?, 1, 1)
//	ON DUPLICATE KEY UPDATE
//	    status = IF((@original_owner_id := owner_id) IS NOT NULL AND (@original_expires_at := expires_at) IS NOT NULL, 1, 1),
//	    owner_id = IF(
//	        @original_owner_id = VALUES(owner_id) OR @original_expires_at < ?,
//	        VALUES(owner_id),
//	        owner_id
//	    ),
//	    expires_at = IF(
//	        @original_owner_id = VALUES(owner_id) OR @original_expires_at < ?,
//	        VALUES(expires_at),
//	        expires_at
//	    ),
//	    epoch = IF(
//	        @original_owner_id != VALUES(owner_id) AND @original_expires_at < ?,
//	        epoch + 1,
//	        epoch
//	    )
func (q *Queries) AcquireLock(ctx context.Context, arg AcquireLockParams) (sql.Result, error) {
	return q.exec(ctx, q.acquireLockStmt, acquireLock,
		arg.Domain,
		arg.LockKey,
		arg.OwnerID,
		arg.ExpiresAt,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
}

const getDomainByDomainAndTasklist = `-- name: GetDomainByDomainAndTasklist :one
SELECT /*+ MAX_EXECUTION_TIME(1000) */
    id,
    domain,
    tasklist,
    metadata,
    partition_count,
    status,
    created_at,
    updated_at
FROM helix_domain
WHERE domain = ?
  AND tasklist = ?
  AND status = 1
`

type GetDomainByDomainAndTasklistParams struct {
	Domain   string `json:"domain"`
	Tasklist string `json:"tasklist"`
}

// GetDomainByDomainAndTasklist
//
//	SELECT /*+ MAX_EXECUTION_TIME(1000) */
//	    id,
//	    domain,
//	    tasklist,
//	    metadata,
//	    partition_count,
//	    status,
//	    created_at,
//	    updated_at
//	FROM helix_domain
//	WHERE domain = ?
//	  AND tasklist = ?
//	  AND status = 1
func (q *Queries) GetDomainByDomainAndTasklist(ctx context.Context, arg GetDomainByDomainAndTasklistParams) (*HelixDomain, error) {
	row := q.queryRow(ctx, q.getDomainByDomainAndTasklistStmt, getDomainByDomainAndTasklist, arg.Domain, arg.Tasklist)
	var i HelixDomain
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Tasklist,
		&i.Metadata,
		&i.PartitionCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getDomainsByDomain = `-- name: GetDomainsByDomain :many
SELECT /*+ MAX_EXECUTION_TIME(1000) */
    id,
    domain,
    tasklist,
    metadata,
    partition_count,
    status,
    created_at,
    updated_at
FROM helix_domain
WHERE domain = ?
  AND status = 1
`

// GetDomainsByDomain
//
//	SELECT /*+ MAX_EXECUTION_TIME(1000) */
//	    id,
//	    domain,
//	    tasklist,
//	    metadata,
//	    partition_count,
//	    status,
//	    created_at,
//	    updated_at
//	FROM helix_domain
//	WHERE domain = ?
//	  AND status = 1
func (q *Queries) GetDomainsByDomain(ctx context.Context, domain string) ([]*HelixDomain, error) {
	rows, err := q.query(ctx, q.getDomainsByDomainStmt, getDomainsByDomain, domain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*HelixDomain{}
	for rows.Next() {
		var i HelixDomain
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Tasklist,
			&i.Metadata,
			&i.PartitionCount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDomainWorker = `-- name: InsertDomainWorker :exec
INSERT /*+ MAX_EXECUTION_TIME(1000) */
INTO helix_worker (domain, unique_id, metadata, last_hb_time, status, version)
VALUES (?, ?, ?, ?, 1, 1)
`

type InsertDomainWorkerParams struct {
	Domain     string         `json:"domain"`
	UniqueID   string         `json:"unique_id"`
	Metadata   sql.NullString `json:"metadata"`
	LastHbTime time.Time      `json:"last_hb_time"`
}

// InsertDomainWorker
//
//	INSERT /*+ MAX_EXECUTION_TIME(1000) */
//	INTO helix_worker (domain, unique_id, metadata, last_hb_time, status, version)
//	VALUES (?, ?, ?, ?, 1, 1)
func (q *Queries) InsertDomainWorker(ctx context.Context, arg InsertDomainWorkerParams) error {
	_, err := q.exec(ctx, q.insertDomainWorkerStmt, insertDomainWorker,
		arg.Domain,
		arg.UniqueID,
		arg.Metadata,
		arg.LastHbTime,
	)
	return err
}

const upsertTasklist = `-- name: UpsertTasklist :exec
INSERT /*+ MAX_EXECUTION_TIME(1000) */
INTO helix_domain (domain, tasklist, metadata, partition_count, status)
VALUES (?, ?, ?, ?, 1)
ON DUPLICATE KEY UPDATE metadata        = VALUES(metadata),
                        partition_count = VALUES(partition_count),
                        status          = 1
`

type UpsertTasklistParams struct {
	Domain         string         `json:"domain"`
	Tasklist       string         `json:"tasklist"`
	Metadata       sql.NullString `json:"metadata"`
	PartitionCount uint32         `json:"partition_count"`
}

// UpsertTasklist
//
//	INSERT /*+ MAX_EXECUTION_TIME(1000) */
//	INTO helix_domain (domain, tasklist, metadata, partition_count, status)
//	VALUES (?, ?, ?, ?, 1)
//	ON DUPLICATE KEY UPDATE metadata        = VALUES(metadata),
//	                        partition_count = VALUES(partition_count),
//	                        status          = 1
func (q *Queries) UpsertTasklist(ctx context.Context, arg UpsertTasklistParams) error {
	_, err := q.exec(ctx, q.upsertTasklistStmt, upsertTasklist,
		arg.Domain,
		arg.Tasklist,
		arg.Metadata,
		arg.PartitionCount,
	)
	return err
}
