// Code generated by MockGen. DO NOT EDIT.
// Source: distribution_algo.go
//
// Generated by this command:
//
//	mockgen -source=distribution_algo.go -destination=distribution_algo_mock.go -package=coordinator
//

// Package coordinator is a generated GoMock package.
package coordinator

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDistributorStrategy is a mock of DistributorStrategy interface.
type MockDistributorStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockDistributorStrategyMockRecorder
	isgomock struct{}
}

// MockDistributorStrategyMockRecorder is the mock recorder for MockDistributorStrategy.
type MockDistributorStrategyMockRecorder struct {
	mock *MockDistributorStrategy
}

// NewMockDistributorStrategy creates a new mock instance.
func NewMockDistributorStrategy(ctrl *gomock.Controller) *MockDistributorStrategy {
	mock := &MockDistributorStrategy{ctrl: ctrl}
	mock.recorder = &MockDistributorStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDistributorStrategy) EXPECT() *MockDistributorStrategyMockRecorder {
	return m.recorder
}

// Distribute mocks base method.
func (m *MockDistributorStrategy) Distribute(ctx context.Context, request DistributionRequest) (*DistributionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Distribute", ctx, request)
	ret0, _ := ret[0].(*DistributionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Distribute indicates an expected call of Distribute.
func (mr *MockDistributorStrategyMockRecorder) Distribute(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Distribute", reflect.TypeOf((*MockDistributorStrategy)(nil).Distribute), ctx, request)
}

// MockWorkerService is a mock of WorkerService interface.
type MockWorkerService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerServiceMockRecorder
	isgomock struct{}
}

// MockWorkerServiceMockRecorder is the mock recorder for MockWorkerService.
type MockWorkerServiceMockRecorder struct {
	mock *MockWorkerService
}

// NewMockWorkerService creates a new mock instance.
func NewMockWorkerService(ctrl *gomock.Controller) *MockWorkerService {
	mock := &MockWorkerService{ctrl: ctrl}
	mock.recorder = &MockWorkerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerService) EXPECT() *MockWorkerServiceMockRecorder {
	return m.recorder
}

// GetActiveWorkers mocks base method.
func (m *MockWorkerService) GetActiveWorkers(ctx context.Context, domain string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveWorkers", ctx, domain)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveWorkers indicates an expected call of GetActiveWorkers.
func (mr *MockWorkerServiceMockRecorder) GetActiveWorkers(ctx, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveWorkers", reflect.TypeOf((*MockWorkerService)(nil).GetActiveWorkers), ctx, domain)
}
