// Code generated by MockGen. DO NOT EDIT.
// Source: objects.go
//
// Generated by this command:
//
//	mockgen -source=objects.go -destination=mocks.go -package=coordinator
//

// Package coordinator is a generated GoMock package.
package coordinator

import (
	context "context"
	reflect "reflect"

	helixDomainMysql "github.com/devlibx/gox-helix/pkg/cluster/recipe/domain/database"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkerService is a mock of WorkerService interface.
type MockWorkerService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerServiceMockRecorder
	isgomock struct{}
}

// MockWorkerServiceMockRecorder is the mock recorder for MockWorkerService.
type MockWorkerServiceMockRecorder struct {
	mock *MockWorkerService
}

// NewMockWorkerService creates a new mock instance.
func NewMockWorkerService(ctrl *gomock.Controller) *MockWorkerService {
	mock := &MockWorkerService{ctrl: ctrl}
	mock.recorder = &MockWorkerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerService) EXPECT() *MockWorkerServiceMockRecorder {
	return m.recorder
}

// GetActiveWorkers mocks base method.
func (m *MockWorkerService) GetActiveWorkers(ctx context.Context, domain string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveWorkers", ctx, domain)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveWorkers indicates an expected call of GetActiveWorkers.
func (mr *MockWorkerServiceMockRecorder) GetActiveWorkers(ctx, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveWorkers", reflect.TypeOf((*MockWorkerService)(nil).GetActiveWorkers), ctx, domain)
}

// MockPartitionService is a mock of PartitionService interface.
type MockPartitionService struct {
	ctrl     *gomock.Controller
	recorder *MockPartitionServiceMockRecorder
	isgomock struct{}
}

// MockPartitionServiceMockRecorder is the mock recorder for MockPartitionService.
type MockPartitionServiceMockRecorder struct {
	mock *MockPartitionService
}

// NewMockPartitionService creates a new mock instance.
func NewMockPartitionService(ctrl *gomock.Controller) *MockPartitionService {
	mock := &MockPartitionService{ctrl: ctrl}
	mock.recorder = &MockPartitionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartitionService) EXPECT() *MockPartitionServiceMockRecorder {
	return m.recorder
}

// GetActivePartitionMappings mocks base method.
func (m *MockPartitionService) GetActivePartitionMappings(ctx context.Context, domain, tasklist string) ([]WorkerPartitionMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivePartitionMappings", ctx, domain, tasklist)
	ret0, _ := ret[0].([]WorkerPartitionMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivePartitionMappings indicates an expected call of GetActivePartitionMappings.
func (mr *MockPartitionServiceMockRecorder) GetActivePartitionMappings(ctx, domain, tasklist any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivePartitionMappings", reflect.TypeOf((*MockPartitionService)(nil).GetActivePartitionMappings), ctx, domain, tasklist)
}

// PersistDistribution mocks base method.
func (m *MockPartitionService) PersistDistribution(ctx context.Context, domain, tasklist string, response *DistributionResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistDistribution", ctx, domain, tasklist, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// PersistDistribution indicates an expected call of PersistDistribution.
func (mr *MockPartitionServiceMockRecorder) PersistDistribution(ctx, domain, tasklist, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistDistribution", reflect.TypeOf((*MockPartitionService)(nil).PersistDistribution), ctx, domain, tasklist, response)
}

// MockDomainService is a mock of DomainService interface.
type MockDomainService struct {
	ctrl     *gomock.Controller
	recorder *MockDomainServiceMockRecorder
	isgomock struct{}
}

// MockDomainServiceMockRecorder is the mock recorder for MockDomainService.
type MockDomainServiceMockRecorder struct {
	mock *MockDomainService
}

// NewMockDomainService creates a new mock instance.
func NewMockDomainService(ctrl *gomock.Controller) *MockDomainService {
	mock := &MockDomainService{ctrl: ctrl}
	mock.recorder = &MockDomainServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainService) EXPECT() *MockDomainServiceMockRecorder {
	return m.recorder
}

// GetTaskListInfo mocks base method.
func (m *MockDomainService) GetTaskListInfo(ctx context.Context, domain, tasklist string) (*helixDomainMysql.HelixDomain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskListInfo", ctx, domain, tasklist)
	ret0, _ := ret[0].(*helixDomainMysql.HelixDomain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskListInfo indicates an expected call of GetTaskListInfo.
func (mr *MockDomainServiceMockRecorder) GetTaskListInfo(ctx, domain, tasklist any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskListInfo", reflect.TypeOf((*MockDomainService)(nil).GetTaskListInfo), ctx, domain, tasklist)
}

// MockDistributorStrategy is a mock of DistributorStrategy interface.
type MockDistributorStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockDistributorStrategyMockRecorder
	isgomock struct{}
}

// MockDistributorStrategyMockRecorder is the mock recorder for MockDistributorStrategy.
type MockDistributorStrategyMockRecorder struct {
	mock *MockDistributorStrategy
}

// NewMockDistributorStrategy creates a new mock instance.
func NewMockDistributorStrategy(ctrl *gomock.Controller) *MockDistributorStrategy {
	mock := &MockDistributorStrategy{ctrl: ctrl}
	mock.recorder = &MockDistributorStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDistributorStrategy) EXPECT() *MockDistributorStrategyMockRecorder {
	return m.recorder
}

// Distribute mocks base method.
func (m *MockDistributorStrategy) Distribute(ctx context.Context, request DistributionRequest) (*DistributionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Distribute", ctx, request)
	ret0, _ := ret[0].(*DistributionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Distribute indicates an expected call of Distribute.
func (mr *MockDistributorStrategyMockRecorder) Distribute(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Distribute", reflect.TypeOf((*MockDistributorStrategy)(nil).Distribute), ctx, request)
}
