// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package helixLockMysql

import (
	"time"
)

type HelixLock struct {
	ID        uint64    `json:"id"`
	Domain    string    `json:"domain"`
	LockKey   string    `json:"lock_key"`
	OwnerID   string    `json:"owner_id"`
	ExpiresAt time.Time `json:"expires_at"`
	Epoch     uint64    `json:"epoch"`
	Status    int8      `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
