// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package helixLockMysql

import (
	"context"
	"database/sql"
	"time"
)

const acquireLock = `-- name: AcquireLock :execresult
INSERT /*+ MAX_EXECUTION_TIME(1000) */ INTO helix_locks
    (domain, lock_key, owner_id, expires_at, epoch, status)
VALUES (?, ?, ?, ?, 1, 1)
ON DUPLICATE KEY UPDATE owner_id   = IF(
        owner_id = VALUES(owner_id) OR expires_at < ?,
        VALUES(owner_id),
        owner_id
                                     ),
                        expires_at = IF(
                                owner_id = VALUES(owner_id) OR expires_at < ?,
                                VALUES(expires_at),
                                expires_at
                                     ),
                        epoch      = IF(
                                owner_id != VALUES(owner_id) AND expires_at < ?,
                                epoch + 1,
                                epoch
                                     ),
                        status     = 1
`

type AcquireLockParams struct {
	Domain      string    `json:"domain"`
	LockKey     string    `json:"lock_key"`
	OwnerID     string    `json:"owner_id"`
	ExpiresAt   time.Time `json:"expires_at"`
	ExpiresAt_2 time.Time `json:"expires_at_2"`
	ExpiresAt_3 time.Time `json:"expires_at_3"`
	ExpiresAt_4 time.Time `json:"expires_at_4"`
}

// AcquireLock
//
//	INSERT /*+ MAX_EXECUTION_TIME(1000) */ INTO helix_locks
//	    (domain, lock_key, owner_id, expires_at, epoch, status)
//	VALUES (?, ?, ?, ?, 1, 1)
//	ON DUPLICATE KEY UPDATE owner_id   = IF(
//	        owner_id = VALUES(owner_id) OR expires_at < ?,
//	        VALUES(owner_id),
//	        owner_id
//	                                     ),
//	                        expires_at = IF(
//	                                owner_id = VALUES(owner_id) OR expires_at < ?,
//	                                VALUES(expires_at),
//	                                expires_at
//	                                     ),
//	                        epoch      = IF(
//	                                owner_id != VALUES(owner_id) AND expires_at < ?,
//	                                epoch + 1,
//	                                epoch
//	                                     ),
//	                        status     = 1
func (q *Queries) AcquireLock(ctx context.Context, arg AcquireLockParams) (sql.Result, error) {
	return q.exec(ctx, q.acquireLockStmt, acquireLock,
		arg.Domain,
		arg.LockKey,
		arg.OwnerID,
		arg.ExpiresAt,
		arg.ExpiresAt_2,
		arg.ExpiresAt_3,
		arg.ExpiresAt_4,
	)
}
